// <auto-generated />
namespace BTC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20171112 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20171112));
        
        string IMigrationMetadata.Id
        {
            get { return "201711130439532_20171112"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
